from ctypes import CFUNCTYPE, c_int, c_uint

from .base_classes import BYTE, DWORD, LONG, LPVOID
from .ctypes_preamble import POINTER, UNCHECKED, String
from .structs.anon_190 import LPNET_DVR_DEVICEINFO_V30
from .structs.anon_198 import NET_DVR_ALARMER
from .structs.net_download_cb_info import NET_DOWNLOAD_CB_INFO
from .structs.net_dvr_cettificate_info import LPNET_DVR_CETTIFICATE_INFO
from .structs.net_dvr_flow_info import LPNET_DVR_FLOW_INFO
from .structs.net_dvr_logonreponseparam import LPNET_DVR_LOGONREPONSEPARAM
from .structs.net_dvr_picview_callbackparam import LPNET_DVR_PICVIEW_CALLBACKPARAM
from .structs.net_dvr_playbackcallbackparam import LPNET_DVR_PLAYBACKCALLBACKPARAM
from .structs.net_dvr_previewcallbackparam import LPNET_DVR_PREVIEWCALLBACKPARAM
from .structs.net_dvr_regcallbackparam import LPNET_DVR_REGCALLBACKPARAM
from .structs.net_dvr_workstate_v40 import LPNET_DVR_WORKSTATE_V40

DATADOWNLOAD = CFUNCTYPE(UNCHECKED(None), LONG, DWORD, POINTER(None), DWORD, POINTER(None))
LOGCALLBACK = CFUNCTYPE(UNCHECKED(None), String, c_uint, c_int, POINTER(None))
CHAR_ENCODE_CONVERT = CFUNCTYPE(UNCHECKED(c_int), String, DWORD, DWORD, String, DWORD, DWORD)
fnCertVerifyResultCallBack = CFUNCTYPE(UNCHECKED(c_int), DWORD, LPNET_DVR_CETTIFICATE_INFO, String)
fLoginResultCallBack = CFUNCTYPE(UNCHECKED(None), LONG, DWORD, LPNET_DVR_DEVICEINFO_V30, POINTER(None))
DOWNLOAD_DATA_CB = CFUNCTYPE(UNCHECKED(c_int), LONG, POINTER(NET_DOWNLOAD_CB_INFO), POINTER(None))
DEV_WORK_STATE_CB = CFUNCTYPE(UNCHECKED(c_int), POINTER(None), c_int, LPNET_DVR_WORKSTATE_V40)
MSGCallBack = CFUNCTYPE(UNCHECKED(None), LONG, POINTER(NET_DVR_ALARMER), POINTER(None), DWORD, POINTER(None))
MSGCallBack_V31 = CFUNCTYPE(UNCHECKED(c_int), LONG, POINTER(NET_DVR_ALARMER), POINTER(None), DWORD, POINTER(None))
NAKEDDAtACALLBACK = CFUNCTYPE(UNCHECKED(None), DWORD, String, DWORD, DWORD, POINTER(None))
REALDATACALLBACK = CFUNCTYPE(UNCHECKED(None), LONG, DWORD, POINTER(BYTE), DWORD, POINTER(None))
ALARMSETUPRESPONSECallBack = CFUNCTYPE(UNCHECKED(LONG), LONG, LONG, POINTER(None))
fAlarmHostSerialDataCallBack = CFUNCTYPE(UNCHECKED(None), LONG, LONG, LONG, String, DWORD, POINTER(None))
FLOWTESTCALLBACK = CFUNCTYPE(UNCHECKED(None), LONG, LPNET_DVR_FLOW_INFO, POINTER(None))
SCREENPICDATACB = CFUNCTYPE(UNCHECKED(None), LONG, DWORD, POINTER(BYTE), DWORD, POINTER(None))
fRemoteConfigCallback = CFUNCTYPE(UNCHECKED(None), DWORD, POINTER(None), DWORD, POINTER(None))
fLongCfgStateCallback = CFUNCTYPE(UNCHECKED(None), LONG, DWORD, LPVOID)
fSearchDBCallBack = CFUNCTYPE(UNCHECKED(None), LONG, DWORD, DWORD, POINTER(BYTE), DWORD, POINTER(None))
PicViewCallBack = CFUNCTYPE(UNCHECKED(LONG), LPNET_DVR_PICVIEW_CALLBACKPARAM, POINTER(None))
DVCS_UPGRADESTATE_CB = CFUNCTYPE(UNCHECKED(None), LONG, POINTER(BYTE), DWORD, POINTER(None))
fGPSDataCallback = CFUNCTYPE(UNCHECKED(None), LONG, DWORD, POINTER(None), DWORD, POINTER(None))
REGCallBack = CFUNCTYPE(UNCHECKED(LONG), LONG, LPNET_DVR_REGCALLBACKPARAM, LPNET_DVR_LOGONREPONSEPARAM, POINTER(None))
PREVIEWRESPONSECallBack = CFUNCTYPE(UNCHECKED(LONG), LONG, LONG, LPNET_DVR_PREVIEWCALLBACKPARAM, POINTER(None))
PLAYBACKRESPONSECallBack = CFUNCTYPE(UNCHECKED(LONG), LONG, LONG, LPNET_DVR_PLAYBACKCALLBACKPARAM, POINTER(None))
VOICERESPONSECallBack = CFUNCTYPE(UNCHECKED(LONG), LONG, LONG, LONG, BYTE, POINTER(None))
