from ctypes import Structure

from ..base_classes import _S, BYTE, DWORD
from ..ctypes_preamble import POINTER
from .net_dvr_singlesubsystemjoininfo_v41 import NET_DVR_SINGLESUBSYSTEMJOININFO_V41


class struct_tagNET_DVR_ALLDECSUBSYSTEMJOININFO_V41(Structure):
    pass

_S(struct_tagNET_DVR_ALLDECSUBSYSTEMJOININFO_V41, [
    ('dwSize', DWORD),
    ('struSingleSubSystemJoinInfo', NET_DVR_SINGLESUBSYSTEMJOININFO_V41 * 120),
    ('byRes', BYTE * 48),
])

NET_DVR_ALLDECSUBSYSTEMJOININFO_V41 = struct_tagNET_DVR_ALLDECSUBSYSTEMJOININFO_V41
LPNET_DVR_ALLDECSUBSYSTEMJOININFO_V41 = POINTER(struct_tagNET_DVR_ALLDECSUBSYSTEMJOININFO_V41)
tagNET_DVR_ALLDECSUBSYSTEMJOININFO_V41 = struct_tagNET_DVR_ALLDECSUBSYSTEMJOININFO_V41
