from ctypes import Structure

from ..base_classes import _S, BYTE, DWORD
from ..ctypes_preamble import POINTER


class struct_tagNET_DVR_ALARMHOST_WIRELESS_BUSINESS_INFO(Structure):
    pass

_S(struct_tagNET_DVR_ALARMHOST_WIRELESS_BUSINESS_INFO, [
    ('dwSize', DWORD),
    ('by3GBusiness', BYTE * 1024),
    ('byRes', BYTE * 32),
])

NET_DVR_ALARMHOST_WIRELESS_BUSINESS_INFO = struct_tagNET_DVR_ALARMHOST_WIRELESS_BUSINESS_INFO
LPNET_DVR_ALARMHOST_WIRELESS_BUSINESS_INFO = POINTER(struct_tagNET_DVR_ALARMHOST_WIRELESS_BUSINESS_INFO)
tagNET_DVR_ALARMHOST_WIRELESS_BUSINESS_INFO = struct_tagNET_DVR_ALARMHOST_WIRELESS_BUSINESS_INFO
