from ctypes import Structure

from ..base_classes import _S, BYTE, DWORD
from ..ctypes_preamble import POINTER


class struct_tagNET_DVR_DEL_RECORD_PASSBACK_MANUAL_COND(Structure):
    pass

_S(struct_tagNET_DVR_DEL_RECORD_PASSBACK_MANUAL_COND, [
    ('dwSize', DWORD),
    ('byDelType', BYTE),
    ('byRes', BYTE * 131),
])

NET_DVR_DEL_RECORD_PASSBACK_MANUAL_COND = struct_tagNET_DVR_DEL_RECORD_PASSBACK_MANUAL_COND
LPNET_DVR_DEL_RECORD_PASSBACK_MANUAL_COND = POINTER(struct_tagNET_DVR_DEL_RECORD_PASSBACK_MANUAL_COND)
tagNET_DVR_DEL_RECORD_PASSBACK_MANUAL_COND = struct_tagNET_DVR_DEL_RECORD_PASSBACK_MANUAL_COND
