from ctypes import Structure

from ..base_classes import _S, BYTE, DWORD
from ..ctypes_preamble import POINTER
from .net_dvr_stream_info import NET_DVR_STREAM_INFO


class struct_tagNET_DVR_MULTI_STREAM_COMPRESSIONCFG_COND(Structure):
    pass

_S(struct_tagNET_DVR_MULTI_STREAM_COMPRESSIONCFG_COND, [
    ('dwSize', DWORD),
    ('struStreamInfo', NET_DVR_STREAM_INFO),
    ('dwStreamType', DWORD),
    ('byRes', BYTE * 32),
])

NET_DVR_MULTI_STREAM_COMPRESSIONCFG_COND = struct_tagNET_DVR_MULTI_STREAM_COMPRESSIONCFG_COND
LPNET_DVR_MULTI_STREAM_COMPRESSIONCFG_COND = POINTER(struct_tagNET_DVR_MULTI_STREAM_COMPRESSIONCFG_COND)
tagNET_DVR_MULTI_STREAM_COMPRESSIONCFG_COND = struct_tagNET_DVR_MULTI_STREAM_COMPRESSIONCFG_COND
