from ctypes import Structure

from ..base_classes import _S, BYTE, DWORD
from ..ctypes_preamble import POINTER
from .net_dvr_stream_info import NET_DVR_STREAM_INFO


class struct_tagNET_DVR_REC_PASSBACK_MANUAL_EXECUTABLE_SEND(Structure):
    pass

_S(struct_tagNET_DVR_REC_PASSBACK_MANUAL_EXECUTABLE_SEND, [
    ('dwSize', DWORD),
    ('struStreamInfo', NET_DVR_STREAM_INFO),
    ('byRes', BYTE * 128),
])

NET_DVR_REC_PASSBACK_MANUAL_EXECUTABLE_SEND = struct_tagNET_DVR_REC_PASSBACK_MANUAL_EXECUTABLE_SEND
LPNET_DVR_REC_PASSBACK_MANUAL_EXECUTABLE_SEND = POINTER(struct_tagNET_DVR_REC_PASSBACK_MANUAL_EXECUTABLE_SEND)
tagNET_DVR_REC_PASSBACK_MANUAL_EXECUTABLE_SEND = struct_tagNET_DVR_REC_PASSBACK_MANUAL_EXECUTABLE_SEND
