from ctypes import Structure

from ..base_classes import _S, BYTE, DWORD
from ..ctypes_preamble import POINTER


class struct_tagNET_DVR_MULTISTREAM_RELATION_CHAN_CFG(Structure):
    pass

_S(struct_tagNET_DVR_MULTISTREAM_RELATION_CHAN_CFG, [
    ('dwSize', DWORD),
    ('dwChannel', DWORD),
    ('byRes', BYTE * 64),
])

NET_DVR_MULTISTREAM_RELATION_CHAN_CFG = struct_tagNET_DVR_MULTISTREAM_RELATION_CHAN_CFG
LPNET_DVR_MULTISTREAM_RELATION_CHAN_CFG = POINTER(struct_tagNET_DVR_MULTISTREAM_RELATION_CHAN_CFG)
tagNET_DVR_MULTISTREAM_RELATION_CHAN_CFG = struct_tagNET_DVR_MULTISTREAM_RELATION_CHAN_CFG
