from ctypes import Union

from ..base_classes import _S, DWORD
from ..ctypes_preamble import POINTER


class union_tagNET_DVR_ALARMHOST_EXCEPTION_PARAM(Union):
    pass

_S(union_tagNET_DVR_ALARMHOST_EXCEPTION_PARAM, [
    ('dwUnionSize', DWORD * 20),
])

NET_DVR_ALARMHOST_EXCEPTION_PARAM = union_tagNET_DVR_ALARMHOST_EXCEPTION_PARAM
LPNET_DVR_ALARMHOST_EXCEPTION_PARAM = POINTER(union_tagNET_DVR_ALARMHOST_EXCEPTION_PARAM)
tagNET_DVR_ALARMHOST_EXCEPTION_PARAM = union_tagNET_DVR_ALARMHOST_EXCEPTION_PARAM
