from ctypes import Structure

from ..base_classes import _S, BYTE, DWORD
from ..ctypes_preamble import POINTER


class struct_tagNET_DVR_DOWNLOAD_CLUSTER_MAINTENANCE_LOG_PARAM_(Structure):
    pass

_S(struct_tagNET_DVR_DOWNLOAD_CLUSTER_MAINTENANCE_LOG_PARAM_, [
    ('dwSize', DWORD),
    ('byType', BYTE),
    ('byRes', BYTE * 255),
])

NET_DVR_DOWNLOAD_CLUSTER_MAINTENANCE_LOG_PARAM = struct_tagNET_DVR_DOWNLOAD_CLUSTER_MAINTENANCE_LOG_PARAM_
LPNET_DVR_DOWNLOAD_CLUSTER_MAINTENANCE_LOG_PARAM = POINTER(struct_tagNET_DVR_DOWNLOAD_CLUSTER_MAINTENANCE_LOG_PARAM_)
tagNET_DVR_DOWNLOAD_CLUSTER_MAINTENANCE_LOG_PARAM_ = struct_tagNET_DVR_DOWNLOAD_CLUSTER_MAINTENANCE_LOG_PARAM_
