"""Compat shim (Hikvision SDK).

Historically this project had its own "loader" and partial bindings.
Now the full wrapper generated by ctypesgen in cida_attendance.sdk is used,
which already includes its cross-platform loader.

This module remains as a compatibility layer with basic helpers.
"""

from __future__ import annotations

import ctypes
import datetime
import platform
import sys
from typing import Callable, Literal

from cida_attendance import sdk

MAX_LEN_XML = 10 * 1024 * 1024
XML_ABILITY_IN_LEN = 1024
XML_ABILITY_OUT_LEN = 3 * 1024 * 1024


class SDKError(Exception):
    pass


def get_sdk_version():
    try:
        version = sdk.NET_DVR_GetSDKVersion()
        build = sdk.NET_DVR_GetSDKBuildVersion()
        return {
            "version": version,
            "build": build,
            "version_string": f"{version >> 24}.{(version >> 16) & 0xFF}.{(version >> 8) & 0xFF}.{version & 0xFF}",
            "build_string": f"{build}",
        }
    except Exception as e:
        return {"error": str(e)}


def get_platform_info() -> dict:
    return {
        "platform": platform.system(),
        "sys_platform": sys.platform,
        "python": sys.version,
    }


def get_last_error(show_msg: bool = True) -> tuple[int, str | None]:
    error = sdk.NET_DVR_GetLastError()
    if not show_msg:
        return error, None

    error_no = ctypes.c_int(error)
    error_msg = sdk.NET_DVR_GetErrorMsg(ctypes.byref(error_no))
    if not error_msg:
        return error, None
    return error, bytes(error_msg).decode("ascii", errors="ignore")


def build_net_dvr_xml_config_input(
    lp_request_url: str,
    lp_in_buffer: str | None = None,
    dw_recv_timeout: int | None = None,
    by_force_encrpt: Literal[0, 1] | None = None,
    by_num_of_multi_part: int | None = None,
    by_mime_type: int | None = None,
):
    """
    Build a `NET_DVR_XML_CONFIG_INPUT` structure.

    Args:
        lp_request_url: XML API request URL (command), for example
            `GET /ISAPI/AccessControl/AcsEvent?format=json`.
        lp_in_buffer: Optional request payload body.
        dw_recv_timeout: Optional receive timeout in milliseconds.
        by_force_encrpt: Optional force-encryption flag (`0` or `1`).
        by_num_of_multi_part: Optional multipart segment count.
        by_mime_type: Optional MIME type indicator for `lp_in_buffer`.

    Returns:
        sdk.NET_DVR_XML_CONFIG_INPUT: Initialized input structure ready to be
        passed to `NET_DVR_STDXMLConfig`.

    Notes:
        - String fields are encoded as ASCII.
        - Internal reserved fields remain at SDK defaults (zero-initialized).
    """
    config = sdk.NET_DVR_XML_CONFIG_INPUT()
    config.dwSize = ctypes.sizeof(config)

    request_buf = ctypes.create_string_buffer(lp_request_url.encode("ascii"))
    config.lpRequestUrl = ctypes.cast(request_buf, ctypes.c_void_p)
    config.dwRequestUrlLen = len(lp_request_url)
    config._request_buf = request_buf

    if lp_in_buffer is not None:
        in_buf = ctypes.create_string_buffer(lp_in_buffer.encode("ascii"))
        config.lpInBuffer = ctypes.cast(in_buf, ctypes.c_void_p)
        config.dwInBufferSize = len(lp_in_buffer)
        config._in_buf = in_buf

    if dw_recv_timeout is not None:
        config.dwRecvTimeOut = int(dw_recv_timeout)

    if by_force_encrpt is not None:
        config.byForceEncrpt = int(by_force_encrpt)

    if by_num_of_multi_part is not None:
        config.byNumOfMultiPart = int(by_num_of_multi_part)

    if by_mime_type is not None:
        config.byMimeType = int(by_mime_type)

    return config


def build_net_dvr_xml_config_output():
    config = sdk.NET_DVR_XML_CONFIG_OUTPUT()
    config.dwSize = ctypes.sizeof(config)

    out_buf = ctypes.create_string_buffer(MAX_LEN_XML)
    config.lpOutBuffer = ctypes.cast(out_buf, ctypes.c_void_p)
    config.dwOutBufferSize = MAX_LEN_XML
    config._out_buf = out_buf

    status_buf = ctypes.create_string_buffer(1024)
    config.lpStatusBuffer = ctypes.cast(status_buf, ctypes.c_void_p)
    config.dwStatusSize = ctypes.sizeof(status_buf)
    config._status_buf = status_buf

    data_buf = ctypes.create_string_buffer(10 * 1024 * 1024)
    config.lpDataBuffer = ctypes.cast(data_buf, ctypes.c_void_p)
    config.byNumOfMultiPart = 0
    config._data_buf = data_buf

    return config


def run_net_dvr_stdxmlconfig(
    user_id: int,
    xml_config_input: sdk.NET_DVR_XML_CONFIG_INPUT,
    xml_config_output: sdk.NET_DVR_XML_CONFIG_OUTPUT,
):
    if not sdk.NET_DVR_STDXMLConfig(
        user_id,
        ctypes.byref(xml_config_input),
        ctypes.byref(xml_config_output),
    ):
        raise SDKError(*get_last_error())


def build_fremoteconfigcallback(
    callback: Callable,
    data_struct: ctypes.Structure = None,
    on_error: Callable = None,
):
    def remote_config_callback(dwType, lpBuffer, dwBufLen, pUserData):
        try:
            if dwType == sdk.NET_SDK_CALLBACK_TYPE_STATUS:
                buffer = ctypes.string_at(lpBuffer, dwBufLen)

                if dwBufLen == 4:
                    status = int.from_bytes(buffer[:4], "little", signed=False)
                    callback(dwType, (status, None))
                elif dwBufLen == 8:
                    status = int.from_bytes(buffer[:4], "little", signed=False)
                    error = int.from_bytes(buffer[4:8], "little", signed=False)
                    callback(dwType, (status, error))
                return

            if dwType == sdk.NET_SDK_CALLBACK_TYPE_PROGRESS:
                callback(dwType, None)
                return

            if dwType == sdk.NET_SDK_CALLBACK_TYPE_DATA:
                if data_struct:
                    detail = ctypes.cast(lpBuffer, ctypes.POINTER(data_struct))
                    callback(dwType, detail.contents)
                else:
                    callback(dwType, (lpBuffer, dwBufLen))
        except BaseException as e:
            if on_error:
                on_error(e)
                return
            raise e

    return sdk.fRemoteConfigCallback(remote_config_callback)


def run_net_dvr_startremoteconfig(
    l_user_id: int,
    dw_command: int,
    lp_in_buffer: ctypes.Structure,
    cb_state_callback: ctypes._CFuncPtr | None = None,
    p_user_data: ctypes.c_void_p | None = None,
) -> int:
    _callback = cb_state_callback
    if _callback is None:
        _callback = sdk.fRemoteConfigCallback(0)

    res = sdk.NET_DVR_StartRemoteConfig(
        l_user_id,
        dw_command,
        ctypes.byref(lp_in_buffer),
        ctypes.sizeof(lp_in_buffer),
        _callback,
        p_user_data,
    )

    if res < 0:
        raise SDKError(*get_last_error())

    return res


def build_net_dvr_user_login_info(device_address, username, password, port=8000):
    login_info = sdk.NET_DVR_USER_LOGIN_INFO()
    login_info.sDeviceAddress = device_address.ljust(
        sdk.NET_DVR_DEV_ADDRESS_MAX_LEN, b"\x00"
    )
    login_info.wPort = int(port)
    login_info.bUseAsynLogin = 0
    login_info.sUserName = username.ljust(sdk.NET_DVR_LOGIN_USERNAME_MAX_LEN, b"\x00")
    login_info.sPassword = password.ljust(sdk.NET_DVR_LOGIN_PASSWD_MAX_LEN, b"\x00")
    return login_info


def build_datetime_to_net_dvr_time(dt: datetime.datetime, structure=None):
    net_dvr_time = structure or sdk.NET_DVR_TIME()
    net_dvr_time.dwYear = dt.year
    net_dvr_time.dwMonth = dt.month
    net_dvr_time.dwDay = dt.day
    net_dvr_time.dwHour = dt.hour
    net_dvr_time.dwMinute = dt.minute
    net_dvr_time.dwSecond = dt.second
    return net_dvr_time


def build_datetime_from_net_dvr_time(
    net_dvr_time,
    tz: datetime.timezone = None,
) -> datetime.datetime:
    return datetime.datetime(
        net_dvr_time.dwYear,
        net_dvr_time.dwMonth,
        net_dvr_time.dwDay,
        net_dvr_time.dwHour,
        net_dvr_time.dwMinute,
        net_dvr_time.dwSecond,
        tzinfo=tz,
    )


def _build_fixed_byte_array(value: str, size: int):
    raw = value.encode("ascii")
    if len(raw) > size:
        raise ValueError(f"value too long ({len(raw)} > {size})")
    return (ctypes.c_ubyte * size).from_buffer_copy(raw.ljust(size, b"\x00"))


def build_net_dvr_acs_event_cond(
    dw_major: int | None = None,
    dw_minor: int | None = None,
    start_time: datetime.datetime | None = None,
    end_time: datetime.datetime | None = None,
    by_card_no: str | None = None,
    by_name: str | None = None,
    by_pic_enable: Literal[0, 1] | None = None,
    by_time_type: Literal[0, 1] | None = None,
    dw_begin_serial_no: int | None = None,
    dw_end_serial_no: int | None = None,
    dw_iot_channel_no: int | None = None,
    w_inductive_event_type: int | None = None,
    by_search_type: Literal[0, 1, 2] | None = None,
    by_event_attribute: Literal[0, 1, 2] | None = None,
    sz_monitor_id: str | None = None,
    by_employee_no: str | None = None,
):
    """Build `NET_DVR_ACS_EVENT_COND` to query access control events.

    Args:
        dw_major: Major event type (`0` means all).
        dw_minor: Minor event type (`0` means all).
        start_time: Start date/time for filtering.
        end_time: End date/time for filtering.
        by_card_no: Card number.
        by_name: Cardholder name.
        by_pic_enable: Include linked image (`0`: no, `1`: yes).
        by_time_type: Time type (`0`: device local time, `1`: UTC).
        dw_begin_serial_no: Start serial number (`0` means all).
        dw_end_serial_no: End serial number (`0` means all).
        dw_iot_channel_no: IoT channel number (`0` is invalid).
        w_inductive_event_type: Inductive event type (`0` is invalid).
        by_search_type: Search mode (`0` reserved, `1` by event source, `2` by monitoring ID).
        by_event_attribute: Event attribute (`0` undefined, `1` valid authentication, `2` others).
        sz_monitor_id: Monitoring resource ID.
        by_employee_no: Employee number (person ID).
    """
    cond = sdk.NET_DVR_ACS_EVENT_COND()
    cond.dwSize = ctypes.sizeof(cond)

    if dw_major is not None:
        cond.dwMajor = dw_major

    if dw_minor is not None:
        cond.dwMinor = dw_minor

    if start_time is not None:
        build_datetime_to_net_dvr_time(start_time, cond.struStartTime)

    if end_time is not None:
        build_datetime_to_net_dvr_time(end_time, cond.struEndTime)

    if by_card_no is not None:
        cond.byCardNo = _build_fixed_byte_array(by_card_no, 32)

    if by_name is not None:
        cond.byName = _build_fixed_byte_array(by_name, 32)

    if by_pic_enable is not None:
        cond.byPicEnable = int(by_pic_enable)

    if by_time_type is not None:
        cond.byTimeType = int(by_time_type)

    if dw_begin_serial_no is not None:
        cond.dwBeginSerialNo = int(dw_begin_serial_no)

    if dw_end_serial_no is not None:
        cond.dwEndSerialNo = int(dw_end_serial_no)

    if dw_iot_channel_no is not None:
        cond.dwIOTChannelNo = int(dw_iot_channel_no)

    if w_inductive_event_type is not None:
        cond.wInductiveEventType = int(w_inductive_event_type)

    if by_search_type is not None:
        cond.bySearchType = int(by_search_type)

    if by_event_attribute is not None:
        cond.byEventAttribute = int(by_event_attribute)

    if sz_monitor_id is not None:
        cond.szMonitorID = sz_monitor_id.ljust(64, "\x00").encode("ascii")

    if by_employee_no is not None:
        cond.byEmployeeNo = _build_fixed_byte_array(by_employee_no, 32)

    return cond


def build_net_dvr_setupalarm_param_v50(
    by_level: int | None = None,
    by_alarm_info_type: int | None = None,
    by_ret_alarm_type_v40: int | None = None,
    by_ret_dev_info_version: int | None = None,
    by_ret_vqd_alarm_type: int | None = None,
    by_face_alarm_detection: int | None = None,
    by_support: int | None = None,
    by_broken_net_http: int | None = None,
    w_task_no: int | None = None,
    by_deploy_type: int | None = None,
    by_sub_scription: int | None = None,
    by_broken_net_http_v60: int | None = None,
    by_alarm_type_url: int | None = None,
    by_custom_ctrl: int | None = None,
):
    setup = sdk.NET_DVR_SETUPALARM_PARAM_V50()
    setup.dwSize = ctypes.sizeof(setup)

    if by_level is not None:
        setup.byLevel = int(by_level)
    if by_alarm_info_type is not None:
        setup.byAlarmInfoType = int(by_alarm_info_type)
    if by_ret_alarm_type_v40 is not None:
        setup.byRetAlarmTypeV40 = int(by_ret_alarm_type_v40)
    if by_ret_dev_info_version is not None:
        setup.byRetDevInfoVersion = int(by_ret_dev_info_version)
    if by_ret_vqd_alarm_type is not None:
        setup.byRetVQDAlarmType = int(by_ret_vqd_alarm_type)
    if by_face_alarm_detection is not None:
        setup.byFaceAlarmDetection = int(by_face_alarm_detection)
    if by_support is not None:
        setup.bySupport = int(by_support)
    if by_broken_net_http is not None:
        setup.byBrokenNetHttp = int(by_broken_net_http)
    if w_task_no is not None:
        setup.wTaskNo = int(w_task_no)
    if by_deploy_type is not None:
        setup.byDeployType = int(by_deploy_type)
    if by_broken_net_http_v60 is not None:
        setup.byBrokenNetHttpV60 = int(by_broken_net_http_v60)
    if by_alarm_type_url is not None:
        setup.byAlarmTypeURL = int(by_alarm_type_url)
    if by_custom_ctrl is not None:
        setup.byCustomCtrl = int(by_custom_ctrl)
    if by_sub_scription is not None:
        setup.bySubScription = int(by_sub_scription)

    return setup
